export const INITIAL_USER = {
  id: 'user_naqib_01',
  name: 'النقيب للمعلومات',
  phone: '777000111',
};

export const INITIAL_ACCOUNTS = [
  {
    id: '1',
    user_id: 'user_naqib_01',
    label: 'المنزل الرئيسي - ADSL',
    username: '01234567',
    balance: '65.40 GB',
    expiry: '25/10/2026',
    status: 'نشط 🟢',
    type: 'ADSL',
    speed: '8 Mbps',
    ip: '10.120.45.18',
    created_at: '2026-01-10T10:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    user_id: 'user_naqib_01',
    label: 'المكتب - يمن فورجي 4G',
    username: '712345678',
    balance: '118.25 GB',
    expiry: '05/11/2026',
    status: 'نشط 🟢',
    type: '4G',
    speed: '30 Mbps',
    ip: '10.88.12.9',
    created_at: '2026-02-15T12:30:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    user_id: 'user_naqib_01',
    label: 'معرض التقنية - ADSL',
    username: '01889900',
    balance: '6.50 GB',
    expiry: '24/09/2026',
    status: 'تحذير 🟡',
    type: 'ADSL',
    speed: '4 Mbps',
    ip: '10.110.33.2',
    created_at: '2026-03-01T08:15:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    user_id: 'user_naqib_01',
    label: 'المستودع - ADSL',
    username: '01554433',
    balance: '0.00 GB',
    expiry: '12/09/2026',
    status: 'منتهي 🔴',
    type: 'ADSL',
    speed: '2 Mbps',
    ip: 'غير متصل',
    created_at: '2026-01-20T14:20:00Z',
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_LOGS = [
  {
    id: 'log-1',
    user_id: 'user_naqib_01',
    action: 'تسجيل دخول ناجح',
    details: 'تم تسجيل الدخول إلى لوحة التحكم بنجاح من المتصفح',
    type: 'auth',
    created_at: 'منذ 5 دقائق',
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'log-2',
    user_id: 'user_naqib_01',
    action: 'تحديث بيانات الحساب',
    details: 'تم فحص وتحديث رصيد اشتراك (المكتب - يمن فورجي 4G)',
    type: 'sync',
    created_at: 'منذ ساعتين',
    timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: 'log-3',
    user_id: 'user_naqib_01',
    action: 'تنبيه انخفاض رصيد',
    details: 'وصل رصيد اشتراك (معرض التقنية - ADSL) إلى أقل من 10 جيجابايت',
    type: 'warning',
    created_at: 'اليوم، 10:15 ص',
    timestamp: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
  },
  {
    id: 'log-4',
    user_id: 'user_naqib_01',
    action: 'فحص دوري تلقائي',
    details: 'فحص خوادم يمن نت وتحديث معلومات الجلسات لجميع الخطوط',
    type: 'system',
    created_at: 'أمس، 08:00 م',
    timestamp: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
  },
];

export const INITIAL_SETTINGS = {
  expiry_alert_enabled: true,
  expiry_alert_days: 3,
  balance_alert_enabled: true,
  balance_alert_threshold: 5,
  daily_report_enabled: true,
  weekly_report_enabled: true,
  telegram_notifications: true,
  email_notifications: false,
};
